version: '3.8'
services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: mppt-go2rtc
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
